### PR TITLE
feat(export): Add createdFrom and createdTo params - Issue #39

### PR DESCRIPTION
**Pull request by junajan**
This PR adds two new parameters `createdFrom` and `createdTo` which specify time boundaries in order export as requested here in this issue: https://github.com/sphereio/sphere-order-export/issues/39

### CODE REVIEW

**Comment by Siilwyn** [comment]
Will review when CI passes and coverage is not decreased. ⛺️

**Comment by junajan** [comment]
@Siilwyn - There was an error due to a higher concurrency when running integration tests against one Sphere project - ` BadRequest: There is already an existing customer with the email...`

I set there a lower concurrency and restarted tests

**Comment by junajan** [comment]
@Siilwyn - not sure why it is still showing a decreased coverage when it grew from `88.177%` to `88.424%` :-(

**Comment by Siilwyn** [comment]
Let's do it differently, adding a 'where predicate' flag so users can filter in all ways possible. This way we can also remove the `fetchHours` flag avoiding a lot of flags.

**Comment by junajan** [comment]
This PR will be replaced by new PR which will allow us to specify a query predicate - based on this issue https://github.com/sphereio/sphere-order-export/issues/42

**Pull request closed without merging**
