### PR TITLE
fix(sync-actions): fix duplicate sync-actions

### LINKED ISSUE #38: duplicate update sync info actions for the same order
@hisabimbola sphere-order-export creates more than one update actions for each order, it creates _number_of_line_items + 1_ update actions however we only need 1 update action per order regardless of the line items.

Sample: [orders_sync_1486046489898.txt](https://github.com/sphereio/sphere-order-export/files/748094/orders_sync_1486046489898.txt)

@MelNiermann

### PR DESCRIPTION
**Pull request by hisabimbola**
fixes #38

### CODE REVIEW

**Comment by junajan** [comment]
@hisabimbola - you have exactly the same problem (with failing builds) as I had in my PR here:
https://github.com/sphereio/sphere-order-export/pull/40
which was fixed by this commit:
https://github.com/sphereio/sphere-order-export/pull/40/commits/6a54cd5850b2292405adc75e34deb5ca1efd4465

But I think that it does not fix the cause which is (I suppose) a failing SFTP connection

**Comment by hisabimbola** [comment]
Yeah @junajan very surprised that your build is passing while mine is failing 😿

**Comment by junajan** [comment]
@hisabimbola that's because I added that fix in this commit 6a54cd5. But still the SFTP export does not work - it just continues after error.

**Comment by hisabimbola** [comment]
@junajan All works for me now

I upgraded the version from ~0.10~

**Comment by junajan** [comment]
Oki.. it should work also on my branch when it gets merged with this one

**Pull request merged**
